name: wedding-card
on: push
jobs:
  echo:
    runs-on: ubuntu-22.04
    steps:
      - run: echo 'Wedding Card, Action Start!'
  pwd-ls:
    name: pwd & ls
    runs-on: ubuntu-22.04
    steps:
      - name: Print Working Directory
        run: pwd
      - name: List Files
        run: ls -al
